### ISSUE TITLE
Azure 6.0

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi-azure#2336]
Prepare for the upcoming major version bump of the upstream terraform-provider-azurerm

- Upstream announcement [Azure Resource Manager: Upcoming Version 4.0 of the Azure Provider | Guides | hashicorp/azurerm | Terraform | Terraform Registry](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/4.0-overview)
- [Upgrade guide](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/4.0-upgrade-guide#removed-resources)

## Implementation Plan

- [x] Review patches for breaking changes
  - [x] Remove case insensitive enums patch or at least reduce the patch size ([design doc](https://docs.google.com/document/d/1RkNH2QRqi0h7nVrJHI3MP74wLDmfe95a7XVJmEtRm5M/edit)).
  - [x] ~Review docs patch for missed changes & move common patterns into docs replacement rules.~ Do this post-release
- [x] Upgrade tests
  - [x] Review, fix existing
  - [x] add new ones for high impact breaking changes (e.g. renames)
- [x] Write release notes
- [x] Audit SDK changes - check alignment with upstream changes (no extra changes/missing resources)
- [x] Test renamed (superseded) resources (e.g. Dashboard) to see if we can add aliases ([tracking doc](https://docs.google.com/spreadsheets/d/1BtdsKmANQX8lKbeZAbljafaCOMc5i_dUSK9KcCYMzk4/edit?gid=0#gid=0)
- [x] Review all build warnings - clear up missing resources.
- [x] Add release verification via ci-mgmt
- [x] [Write and publish blog post](https://github.com/pulumi/docs/pull/12915)
- [ ] Update templates
- [ ] Update examples

**Comment by danielrbradley** [comment]
## 6th Sept Status Update

### What we got done this week

- Completed migration to the new upgrade test framework which has given us much higher confidence in our changes.
- Completed an audit of all possible high-impact breaking changes around the case-insensitive enums.
- Completed proof of concepts of using `TransformFromState` to auto-fix casing when upgrading to avoid replacements.
- Started writing tests for the most critical of resources affected. Found that a number of resources already fix their own state without us adding `TransformFromState`

### What we’ll do next week

- Complete case sensitive enum testing for 8 more resources.
- Investigate the additional "superseded" resources to check if we can add additional aliases.
- Write our release notes.

### Upcoming deliverable
- 12th September: PR ready for review

**Comment by danielrbradley** [comment]
## 13th Sept Status Update

### What we got done this week

- Implemented state fixes and tests for case insentitive enum changes.
- Implemented aliases, state fixes and tests for renamed or superceded resources.
- Added release verification tests - initially covering nodejs, dotnet and go SDKs and the provider acquisition.
- Fixed mentions of terraform in the import docs which were causing a large number of build warnings.

### What we’ll do next week

- Complete the migration guide.
- Invite wider team PR review.

### Upcoming deliverable

- Beta.1 release coming later today after team sync.
- Final merge and release expected next week.

**Comment by danielrbradley** [comment]
## 20th Sept Status Update
### What we got done this week

- Completed the migration guide
- Added several more aliases to ease customer migration
- Cut the first beta release which confirmed that the release was functional via the release verification tests

### What we’ll do next week

- Release
- Blog post

### Upcoming deliverable

- Blog post

**Comment by danielrbradley** [comment]
## 27th Sept Status Update
### What we got done this week
* [Completed the release](https://github.com/pulumi/pulumi-azure/releases/tag/v6.0.0)
* Wrote and published the [blog post
](https://www.pulumi.com/blog/azure-v6-release/)

### What we’ll do next week
* Update examples and templates

### Upcoming deliverable
* Examples and Templates PRs
